steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "DEVELOP=${_DEVELOP}" >> .env
        echo "DATABASE_URL=${_DATABASE_URL}" >> .env
        echo "NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}" >> .env
        echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}" >> .env
        echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}" >> .env
        echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}" >> .env
        echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}" >> .env
        echo "NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}" >> .env
        echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}" >> .env
        echo "NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL=${_NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL}" >> .env
        echo "NEXT_PUBLIC_FIREBASE_PRIVATE_KEY=${_NEXT_PUBLIC_FIREBASE_PRIVATE_KEY}" >> .env

        docker build -f Dockerfile -t gcr.io/$PROJECT_ID/coauthor:$COMMIT_SHA .

  - name: "gcr.io/google-appengine/exec-wrapper"
    args: []

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/coauthor:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "coauthor"
      - "--image"
      - "gcr.io/$PROJECT_ID/coauthor:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
images:
  - "gcr.io/$PROJECT_ID/coauthor:$COMMIT_SHA"
timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
