services:
  coauthor_db:
    image: postgres:17
    hostname: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M

  # db_migrate:
  #   build:
  #     dockerfile: Dockerfile.migrate
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   entrypoint: "npm run prisma:deploy"

volumes:
  db_data:
    driver: local
