name: Deploy to Production

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./package.json
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install dependencies
        working-directory: ./
        run: npm ci

      - name: Generate Prisma schema
        working-directory: ./
        run: npm run prisma:generate

      - name: Run tests
        working-directory: ./
        run: npm test --bail --maxWorkers=100% --watchAll=false -- --coverage

  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        env:
          _DATABASE_URL: ${{ secrets.DATABASE_URL }}
          _NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          _NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          _NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL: ${{ secrets.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL }}
          _NEXT_PRIVATE_FIREBASE_PRIVATE_KEY: ${{ secrets.NEXT_PRIVATE_FIREBASE_PRIVATE_KEY }}
        run: |
          echo "DATABASE_URL=${_DATABASE_URL}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL=${_NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL}" >> .env.production
          echo "NEXT_PRIVATE_FIREBASE_PRIVATE_KEY=${_NEXT_PRIVATE_FIREBASE_PRIVATE_KEY}" >> .env.production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACCESS_AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build Docker Image
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} -f Dockerfile .
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          echo "image_id=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      - name: Migrate Database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npm install @prisma/cli@6.1.0
          npx prisma migrate deploy

      - name: Update ECS Task Definition
        run: |
          echo "Updating ECS Task Definition"
          sed -i "s|\[AWS_REGION\]|${{ secrets.AWS_REGION  }}|g" ./deploy-process/coauthor-production-task.json
          sed -i "s|\[TASK_ROLE_ARN\]|${{ secrets.TASK_ROLE_ARN  }}|g" ./deploy-process/coauthor-production-task.json
          sed -i "s|\[TASK_EXECUTION_ROLE_ARN\]|${{ secrets.TASK_EXECUTION_ROLE_ARN  }}|g" ./deploy-process/coauthor-production-task.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: coauthor-production-task.json
          task-definition-family: coauthor-production-task
          container-name: app
          image: ${{ steps.build-image.outputs.image }}
          environment-variables: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}"
            "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}"
            "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}"
            "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}"
            "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}"
            "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}"
            "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}"
            "NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL=${{ secrets.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL }}"
            "NEXT_PRIVATE_FIREBASE_PRIVATE_KEY=${{ secrets.NEXT_PRIVATE_FIREBASE_PRIVATE_KEY }}"

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: coauthor-production-service
          cluster: ${{ secrets.AWS_ECS_CLUSTER_NAME }}
